In [2]:
import numpy as np
import matplotlib.pyplot as plt

__1.1, 1.2 & 1.3__

In [55]:
#create matrix
m =np.array([[1, 2], [3, 4]])

#create inverse
n = np.linalg.inv(m)

#multiply inverse by matrix for corresponding identity matrix
a = m @ n

#multiply matrix by corresponding identity matrix to get the initial matrix
a @ m

array([[1., 2.],
       [3., 4.]])

In [21]:
#create matrix
m = np.array([[1, 1], [0, 1]])

#create inverse
n = np.linalg.inv(m)

#multiply inverse by matrix for corresponding identity matrix
a = m @ n

#multiply matrix by corresponding identity matrix to get the initial matrix
a @ m

array([[1., 1.],
       [0., 1.]])

In [22]:
#create matrix
m =np.array([[1, 2, 3], [0, 2, 3], [0, 0, 3]])

#create inverse
n = np.linalg.inv(m)

#multiply inverse by matrix for corresponding identity matrix
a = m @ n

#multiply matrix by corresponding identity matrix to get the initial matrix
a @ m

array([[1., 2., 3.],
       [0., 2., 3.],
       [0., 0., 3.]])

__1.4__

In [62]:
A = np.array([[1, 1, 1], [0, 1, 0], [1, 0, 1]])

__1.5__

In [24]:
np.linalg.det(A)

0.0

__1.6__

In [25]:
np.linalg.eig(A)

(array([2., 0., 1.]), array([[ 0.70710678, -0.70710678,  0.        ],
        [ 0.        ,  0.        ,  0.70710678],
        [ 0.70710678,  0.70710678, -0.70710678]]))

__1.7__

In [90]:
identity = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
B = A + identity
B

array([[2, 1, 1],
       [0, 2, 0],
       [1, 0, 2]])

__1.8__

In [58]:
np.linalg.eig(B)

(array([3., 1., 2.]), array([[ 0.70710678, -0.70710678,  0.        ],
        [ 0.        ,  0.        ,  0.70710678],
        [ 0.70710678,  0.70710678, -0.70710678]]))

__1.9__

In [59]:
B_inverse = np.linalg.inv(B)
B_inverse

array([[ 0.66666667, -0.33333333, -0.33333333],
       [ 0.        ,  0.5       ,  0.        ],
       [-0.33333333,  0.16666667,  0.66666667]])

In [60]:
B_inverse @ B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
B_inverse @ B - identity 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

__as expected, the b_inverse dot b produces an identity matrix and therefore b_inverse dot b minus an identity matrix produces a zero matrix__

__1.10__

In [93]:
A = np.array([[1, 1, 1], [0, 1, 0], [1, 0, 1]])

def busted(e):
    B = A + e * identity
    return(B)

In [98]:
e = .1
B = A + e * identity
np.linalg.eig(B)

(array([2.1, 0.1, 1.1]), array([[ 0.70710678, -0.70710678,  0.        ],
        [ 0.        ,  0.        ,  0.70710678],
        [ 0.70710678,  0.70710678, -0.70710678]]))

In [99]:
B_inverse = np.linalg.inv(B)
B_inverse @ B - identity

array([[ 8.88178420e-16,  8.88178420e-16,  9.09325525e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.88178420e-16, -8.88178420e-16, -6.66133815e-16]])

In [102]:
def busted(e):
    
    #create matrix
    B = A + e * identity
    
    #create inverse
    B_inverse = np.linalg.inv(B)
    
    #multiply inverse by matrix for corresponding identity matrix
    i = B_inverse @ B
    
    #SHOULD give zero matrix but since it wont...
    r = i - identity

    return(r)


In [103]:
busted(.1)

array([[ 8.88178420e-16,  8.88178420e-16,  9.09325525e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.88178420e-16, -8.88178420e-16, -6.66133815e-16]])

In [104]:
busted(.01)

array([[0.00000000e+00, 7.10542736e-15, 1.76080267e-15],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.77635684e-15]])

In [105]:
busted(.000000001)

array([[0.00000000e+00, 0.00000000e+00, 5.00000062e-10],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

__below is the smallest value(greates number of zeros) that did not produce an singular matrix__

In [113]:
busted(.000000000000001)

array([[0.00000000e+00, 0.00000000e+00, 5.27355937e-16],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])